### ISSUE TITLE
Frontend for metrics

### ISSUE THREAD

**Issue by shah-ee** [hmrc/platform-progress-metrics#4]
# Context

As part of [this ticket](https://jira.tools.tax.service.gov.uk/browse/BDOG-1391) we want to give a pie-like view of our metrics. probably a dashboard view.

# Observations

- https://github.com/hmrc/catalogue-frontend already has an endpoint that surfaces Pie chart views about dependencies: [example](https://catalogue.tax.service.gov.uk/dependencyexplorer/results?group=com.typesafe.play&artefact=play&team=&flag=latest&scope=compile&versionRange=%5B0.0.0%2C%29&asCsv=false)
- The template behind that page is here: https://github.com/hmrc/catalogue-frontend/blob/2afae67fb4957744fb0f426eaa96cfe1f31ebde9/app/views/DependencyExplorerPage.scala.html
- The model behind it, is [this](https://github.com/hmrc/catalogue-frontend/blob/31e283bdedf20061b35de5151b4da0fcd68ea91b/app/uk/gov/hmrc/cataloguefrontend/DependencyExplorerController.scala#L213-L216)

  ie:

  ```scala
  case class PieData(
    title: String,
    results: Map[String, Int]
  )
  ```

- Catalogue-front-end [uses](https://github.com/hmrc/catalogue-frontend/blob/2afae67fb4957744fb0f426eaa96cfe1f31ebde9/app/views/DependencyExplorerPage.scala.html#L274) ie:

  ```javascript
  var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
  ```
  Here is Google's visualisation library to draw the pie charts: https://developers.google.com/chart/interactive/docs/gallery

- I'd argue Gauge charts are more intuitive for our purposes. see here: https://developers.google.com/chart/interactive/docs/gallery/gauge

# Questions

- Should the metrics FE be done in catalogue-front-end? :thinking: 
- how do we want to present a list of pie-charts? fixed width? say 5 columns? with the widths being screen-size dependent?

# Tasks

- [x] Create a basic template showing a basic hard-coded pie chat
- [x] create a basic template showing a fixed list of pie charts
- [x] create model classes
- [ ] change the controller and make the it fetch the actual data to display results

**Comment by shah-ee** [comment]
# Gauge vs Pie chart

https://jsfiddle.net/shahx/e1L8objf/
vs 
https://jsfiddle.net/shahx/hpwx9475/2/

ie:

**Comment by shah-ee** [comment]
demo of multiple charts stacked together:

![Screenshot from 2021-08-11 20-19-41](https://user-images.githubusercontent.com/87760387/129089929-2cbbf342-7faf-42bf-8dc4-5386e0ab7ec8.png)

**Comment by shah-ee** [comment]
# Update

Demo-ed it to the team and we decided it's best to go with the Pie chart option.

**Comment by shah-ee** [comment]
Progress report: 

managed to get the charts in a grid:

![Screenshot from 2021-08-16 15-19-45](https://user-images.githubusercontent.com/87760387/129578582-b49faeee-e2ae-48db-beb8-44d00b209c5f.png)

next step is to change the controller to call the actual endpoint from platform-progress-metrics api and fetch the data dynamically instead of the hardcoded stuff.

**Comment by shah-ee** [comment]
Frontend work is now probably complete. need to:

- [ ] deploy #1 and have catalogue front-end read from it.

**Comment by shah-ee** [comment]
![Screenshot from 2021-08-17 20-01-49](https://user-images.githubusercontent.com/87760387/129785295-363b945f-d490-4662-9eba-3d48e2630736.png)
